-
  name: git-push
  hosts: localhost
  tasks:
    - name: exec deploy
      script: deploy.sh
-
  name: git-clone
  hosts: amazon
  tasks:
    - name: git clone
      command: 'sh ec2.sh' 	
#      git: 
#        repo: 'https://github.com/DivySrivastava/Pudding.git' 
#        dest: '/home/Pudding'
#        clone: no
#        update: yes
#        force: true
#        become: yes
#        become_method: enable
#        become_user: su
